README.md
Added a space between URL and trailing slash for brokerClientURL in CRA docs
=> Fix typo in README for Container Registry Agent

README.md
This PR fixes broken documentation link to Snyk Broker Code Agent.
=> docs: fix broken link for code agent

.github/workflows/helm-releaser.yaml
It was *very* out of date, and the upgrade should fix the 404 errors we see when trying to release.
=> chore: bump helm action to 1.4.1

README.md
Adding following to README.md:
1. Instructions for setting ```brokerServerUrl``` value for different multi-tenant environments
2. Add ```brokerServerUrl``` to Configuration table
=> docs: add multi-tenant instructions

.gitleaks.toml
What:
- Updating `.gitleaks.toml` so it doesn't cause pipeline failure when test secret is detected
=> fix: updating gitleaks toml

charts/snyk-broker/Chart.yaml, charts/snyk-broker/templates/broker_deployment.yaml, charts/snyk-broker/templates/cacert_configmap.yaml, charts/snyk-broker/tests/__snapshot__/broker_cra_deployment_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_cra_deployment_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_apprisk_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_configmap_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_configmap_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_customaccept_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_customaccept_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_ingress_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_ingress_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_scm_token_pool_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/cra_deployment_digitalocean_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/cra_deployment_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/cra_deployment_harbor_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/cra_deployment_test.yaml.snap, charts/snyk-broker/values.yaml
This PR fixes an issue when cacert configmap was not created with defined `caCertFile` value.
Failing unit tests (and snapshots) after fix show that exactly this envvar and volume was not mounted to the deployment.
```
- asserts[0] `matchSnapshot` fail
Template:	snyk-broker/templates/broker_deployment.yaml
DocumentIndex:	0
Path:	
Expected to match snapshot 1:
--- Expected
+++ Actual
@@ -48,2 +48,6 @@
value: "false"
+            - name: CA_CERT
+              value: /home/node/cacert/cacert
+            - name: NODE_EXTRA_CA_CERTS
+              value: /home/node/cacert/cacert
- name: ACCEPT_CODE
@@ -93,6 +97,12 @@
runAsUser: 1000
-          volumeMounts: null
+          volumeMounts:
+            - mountPath: /home/node/cacert
+              name: RELEASE-NAME-snyk-broker-cacert-volume
+ …
```
=> fix: create volume mount with cacert when caCertFile is defined

.editorconfig, charts/snyk-broker/Chart.yaml, charts/snyk-broker/templates/broker_deployment.yaml, charts/snyk-broker/templates/secrets.yaml, charts/snyk-broker/tests/__snapshot__/broker_cra_deployment_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_cra_deployment_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_apprisk_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_artifactory_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_configmap_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_configmap_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_customaccept_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_customaccept_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_ingress_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_ingress_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_scm_token_pool_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/cra_deployment_digitalocean_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/cra_deployment_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/cra_deployment_harbor_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/cra_deployment_test.yaml.snap, charts/snyk-broker/tests/broker_deployment_artifactory_test.yaml
This PR creates a secret if `scmType: artifactory` because ARTIFACTORY_URL may contain `user:password` in URL as Basic auth.
Following secrets will be created because they may contain credentials:
- artifactory-url
- artifactory-broker-client-validation-url
Additionally BROKER_CLIENT_URL will be set for consistency with other scmTypes.
=> fix: use secret for artifactoryUrl

charts/snyk-broker/Chart.yaml, charts/snyk-broker/templates/broker_deployment.yaml, charts/snyk-broker/templates/secrets.yaml, charts/snyk-broker/tests/__snapshot__/broker_cra_deployment_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_cra_deployment_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_apprisk_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_artifactory_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_configmap_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_configmap_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_customaccept_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_customaccept_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_ingress_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_ingress_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_nexus_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_scm_token_pool_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/cra_deployment_digitalocean_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/cra_deployment_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/cra_deployment_harbor_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/cra_deployment_test.yaml.snap, charts/snyk-broker/tests/broker_deployment_nexus_test.yaml
This PR creates a secret for **brokerClientValidationUrl** if it's defined for `scmType: nexus/nexus2`, because URL may contain *username:password*.
Additionally we specify `chart.version` in broker_deployment_nexus_test.yaml` to overcome the issues with bumping snapshots because of new releases.
> action run to confirm: https://github.com/snyk/snyk-broker-helm/actions/runs/8638297257/job/23682434195#step:4:763
=> fix: nexus broker client validation url as secret

charts/snyk-broker/Chart.yaml, charts/snyk-broker/templates/cra_deployment.yaml, charts/snyk-broker/tests/__snapshot__/broker_cra_deployment_extraPodSpecs_test.yaml.snap, charts/snyk-broker/tests/broker_cra_deployment_extraPodSpecs_test.yaml, charts/snyk-broker/tests/fixtures/extra_pod_spec_values.yaml, charts/snyk-broker/values.yaml
Allows `extraPodSpecs` to be specified for Container Registry Agent
=> fix: extra pod specs for cra

.gitleaksignore, charts/snyk-broker/Chart.yaml, charts/snyk-broker/tests/broker_deployment_ca_test.yaml, charts/snyk-broker/values.schema.json
- Expect certificates provided as values to have `-----BEGIN CERTIFICATE-----` as header, and `-----END CERTIFICATE-----` as footer
- We do not expect any private key material, nor do we support certificates in other formats
=> fix: validate certificate format

charts/snyk-broker/Chart.yaml, charts/snyk-broker/templates/_helpers.tpl, charts/snyk-broker/templates/broker_deployment.yaml, charts/snyk-broker/templates/code_agent_deployment.yaml, charts/snyk-broker/templates/cra_deployment.yaml, charts/snyk-broker/tests/broker_cra_deployment_disable_tls_test.yaml, charts/snyk-broker/values.schema.json
- Handle cases where `tlsRejectUnauthorized` is set to `false` (boolean) or `"0"` (string)
- Previously setting this value to `false` has no effect
- Passing `"0"` via `--set` causes Helm to cast `"0"` as `0`, which has fails input validation
=> fix: correctly set tlsRejectUnauthorized

charts/snyk-broker/Chart.yaml, charts/snyk-broker/templates/_helpers.tpl, charts/snyk-broker/templates/broker_deployment.yaml, charts/snyk-broker/templates/code_agent_deployment.yaml, charts/snyk-broker/tests/broker_deployment_proxy.yaml, charts/snyk-broker/tests/broker_deployment_proxy_test.yaml, charts/snyk-broker/values.schema.json, charts/snyk-broker/values.yaml
- Fixes schema validation to allow `noProxy` to be set _without_ protocol
- Convention for `NO_PROXY` is a comma separated list of domain names only, previously `values.schema.json` was asserting for the presence of a protocol incorrectly.
=> fix: correctly specify NO_PROXY without protocol [HYB-593]

charts/snyk-broker/Chart.yaml, charts/snyk-broker/templates/_notes.tpl, charts/snyk-broker/templates/_scmConfig.tpl, charts/snyk-broker/tests/broker_deployment_rename_secrets_test.yaml
- Removes the erroneous enforcement of uniqueness for nexus external secret keys
- Tests secret values may all be sourced from the same k8s secret object
=> fix: allow nexus url and base url to share secret, force unique keys

charts/snyk-broker/Chart.yaml, charts/snyk-broker/templates/NOTES.txt, charts/snyk-broker/templates/broker_deployment.yaml, charts/snyk-broker/tests/broker_deployment_ca_test.yaml, charts/snyk-broker/tests/broker_deployment_tls_test.yaml
- Adds missing `volumeMount` for ca-cert and tls secrets if specified externally
=> fix: missing volumemount for ca cert, tls

charts/snyk-broker/Chart.yaml, charts/snyk-broker/templates/_helpers.tpl, charts/snyk-broker/templates/broker_deployment.yaml, charts/snyk-broker/tests/__snapshot__/broker_cra_deployment_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_cra_deployment_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_apprisk_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_artifactory_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_customaccept_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_customaccept_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_ingress_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_ingress_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_scm_token_pool_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/cra_deployment_digitalocean_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/cra_deployment_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/cra_deployment_harbor_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/cra_deployment_test.yaml.snap, charts/snyk-broker/tests/broker_deployment_labels_test.yaml
- Add any labels to broker pods
- Previously labels were applied at the ReplicaSet level only
=> fix: add labels to containers

charts/snyk-broker/tests/__snapshot__/broker_deployment_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_ingress_disablesuffixes_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_ingress_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_scm_token_pool_test.yaml.snap, charts/snyk-broker/tests/__snapshot__/broker_deployment_test.yaml.snap, charts/snyk-broker/values.yaml
- Enables AppRisk by default
- AppRisk is included for Snyk Enterprise users by default
=> fix: enable apprisk by default [HYB-651]

.releaserc
This PR attempts to resolve the semantic release error complaining that "the option must be an array of plugin definitions"
=> fix: Update exec plugin config to use an array of objects

.circleci/config.yml
This PR bumps chart-releaser version to v1.7.0.
We use fix prefix to trigger semantic-release to generate a new fix version so index.yaml is synced.
=> fix: bump chart-releaser to v1.7.0

.releaserc
There is a bug that prevents semantic release from updating the index file using SSH, it expects HTTPS
https://github.com/helm/chart-releaser/issues/124#issuecomment-850799366
=> fix: Fix semantic release repository URL

.circleci/config.yml, .gitignore, .releaserc, package-lock.json, package.json
This PR ensures that .git/config will return https://<git-url> by chart-releaser when calling `git remote get-url --push origin` command.
Additionally semantic-release NPM package is locked by using package.json and installing dependencies via `npm ci` command. Otherwise we'll always fetch latest semantic-release version with (maybe) breaking changes.
=> fix: configure github origin for chart-releaser

.releaserc
This PR fixes the release process using `chart-releaser`:
- create GH releases via `chart-releaser` and not with `semantic-release/github` plugin
- update index.yaml file correctly to use urls from GH releases
Fixes #158.
p.s.: changes are tested on the fork repo: https://github.com/pavel-snyk/snyk-broker-helm
=> chore: fix release process

README.md
This PR fixes broken link after splitting classic and universal Broker in Doc portal.
Fixes #164.
=> chore: fix broken link to classic documentation
